{% set name = "secimtools" %}
{% set version = "21.3.4.1" %}
{% set hash_type = "sha256" %}
{% set hash_value = "90e79ff24c2c3f974a760594364555f59f3f993440c77aeb838472880015eade" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  url: https://files.pythonhosted.org/packages/ec/1b/831c68446b825b00aad03e1c86f801cb78dcdab1abaa86af80d778beae55/{{ name }}-{{ version }}.tar.gz
  '{{ hash_type }}': '{{ hash_value }}'

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - bioconductor-impute
    - lxml
    - matplotlib
    - matplotlib-venn
    - numpy >=1.16
    - palettable
    - pandas
    - pymc
    - r-glmnet
    - rpy2
    - scikit-learn
    - scipy
    - seaborn
    - statsmodels

test:
  imports:
    - secimtools
    - secimtools.anovaModules
    - secimtools.dataManager
    - secimtools.visualManager

about:
  home: https://github.com/secimTools/SECIMTools
  license: MIT License
  license_family: MIT
  summary: Metabolomics tools from the SECIM project
  description: 'SECIMTools project aims to develop a suite of tools for processing of metabolomics data, which can be run in a standalone mode or via Galaxy Genomics Framework.'
  doc_url: ''
  dev_url: ''

extra:
  recipe-maintainers: 'om@rc.ufl.edu'
